### ISSUE TITLE
Reorganize scripts directory

### ISSUE THREAD

**Issue by cvvergara** [cvvergara/workshop#10]
Organize scripts directory by chapter so that in the future it looks like
```
ls scirpts
chapter_4
chapter_5
chapter_6
```

# Tasks:
- [x] create `chapter-4`
- [x] move current contents to chapter-4
- [x] create the `CMakeLists.txt` that will work the set of chapters
- [x] make things work locally in the computer

**Comment by cvvergara** [comment]
changed the dash to underscore on the first message
